# Generated by Django 4.2.16 on 2024-09-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='media/profile_pics/default.jpeg', upload_to='profile_pics'),
        ),
    ]
