# Generated by Django 4.2.16 on 2024-09-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uploaded_at',
        ),
    ]
