# Generated by Django 4.2.16 on 2024-09-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.jpeg', upload_to='profile_pics'),
        ),
    ]
