# Generated by Django 4.2.16 on 2024-09-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
